repos:
  # isort
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]

  # Black formatter
  - repo: https://github.com/psf/black
    rev: 23.10.1
    hooks:
      - id: black
        language_version: python3.10

  # Flake8 linter
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies: [
          'flake8-bugbear',
          'flake8-import-order',
        ]
        args: [
          '--max-line-length=120',
          '--ignore=E203,W503'
        ]

  # Mypy type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
    hooks:
      - id: mypy
        args: [
          '--ignore-missing-imports',
          '--allow-untyped-defs'
        ]
        additional_dependencies: [
          'types-all'
        ]

  # General Python code checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: debug-statements